### ISSUE TITLE
Zebranie informacji dotyczących postawienia serwera

### ISSUE THREAD

**Issue by hardzik96** [Impognomik/Projekcik#1]

**Comment by Impognomik** [comment]
Rozpoczęcie zbierania informacji, zorientowanie się w możliwych rozwiązaniach problemu

**Comment by Impognomik** [comment]
Rozpoczęcie tworzenia kompendium wiedzy dotyczącej tematu

**Comment by Impognomik** [comment]
Ciekawe artykuły:

http://komputery.spryciarze.pl/zobacz/jak-postawic-domowy-serwer-widziany-z-internetu
http://www.pcformat.pl/Wlasny-FTP,a,1608
http://blog.avensome.net/serwer-ssh-pod-windows/

**Comment by Impognomik** [comment]
Zbierałam informację dotyczących serwera ssh, sposobów go postawienia

**Comment by Impognomik** [comment]
Dzisiaj poznałam topologię sieci komputerowych, zgłębiłam temat protokołów sieciowych, adresów IP i MAC

**Comment by Impognomik** [comment]
Dzisiaj zapoznałam się z serwerem HTTP - Apache. Ponadto rozważam w jakim środowisku najłatwiej będzie działać (windows czy linuks). Wiem że system linuksowy jest lepiej dostosowany do tworzenia serwerów. Główny problem polega na tym że go nie posiadam. Aby wykorzystać linuxa musiałabym zainstalować drugi system operacyjny lub stworzyć maszynę wirtualną. To jest kwestia jeszcze do przemyślenia

**Comment by Impognomik** [comment]
Dzisiaj podjęłam udaną próbę stworzenia maszyny wirtualnej. Niestety problem pojawił się przy ściągnięciu systemu operacyjnego linuks na mój komputer. Na tą chwilę zajmie to jeszcze siedem godzin.

**Comment by Impognomik** [comment]
Dzisiaj dalsza część walki z maszyną wirtualną, ściągałam różne systemy operacyjne z rodziny linuksowych i instalowałam na maszynie. Niestety żaden nie chciał współpracować. Problem nadal nie rozwiązany

**Comment by Impognomik** [comment]
Uważam że, zebrałam dostateczną ilość informacji aby przejść do prób stworzenia serwera
