### ISSUE TITLE
Rozwijanie działania serwera

### ISSUE THREAD

**Issue by Impognomik** [Impognomik/Projekcik#13]

**Comment by Impognomik** [comment]
Analiza dokonanych i przewidzianych działań:
- [x] Stworzenie maszyny wirtualnej
- [x] Postawienie serwera (instalacja apache, php, mysql)
- [ ] Połączenie z zewnętrzną siecią
- [ ] Dodanie możliwości dodawania plików przez urzytkowników

**Comment by Impognomik** [comment]
Dzisiaj próbowałam rozwiązać problem zmiennego adresu ip. Istnieje możliwość uzyskania stałego adresu domeny (darmowej) i ściągnięcia programu który stale szczytuje nasze zmienne ip i przypisuje mu stały adres domeny. Niestety na razie to rozwiązanie nie zadziałało. Mam wrażenie że problem może tkwić w niewłaściwej konfiguracji portów.

**Comment by Impognomik** [comment]
Dzisiaj dalej walczyłam z połączeniem serwera z zewnętrzną siecią. Niestety wszystkie dotychczasowe rozwiązania, które znalazłam w internecie nie zaowocowały jakimkolwiek sukcesem. Jutro będę walczyć dalej.

**Comment by konrad966** [comment]
Rozwój serwera wymaga jeszcze pracy, budowy. Nadal jest jeszcze kilka rzeczy do poprawienia, ale zostawiamy to na następny sprint.
