### ISSUE TITLE
Tworzenie zapisu dokumentacji

### ISSUE THREAD

**Issue by Impognomik** [Impognomik/Projekcik#14]

**Comment by hardzik96** [comment]
W dniu dzisiejszym zajęłam się wstępnym pisaniem dokumentacji - tzn wypisalam w punktach zrealizowane przez nas czynnosci podczas wykonywania kolejnych sprintow. Misze jeszcze to wszystko obrac w lepsze slowa i rozwinac poszczegolne tematy.

**Comment by RafikMul** [comment]
Zrobiony spis treści. Dowiedziałem się w jakiej formie ma być oddana dokumentacja przez co na samym końcu poprawię ją żeby była w odpowiednim stanie do oddania

**Comment by Impognomik** [comment]
Dzisiaj skupiłam się nad dopracowywaniem dokumentacji, opisaniem relacji w grupie i sposobów współpracy

**Comment by konrad966** [comment]
Dzisiaj zająłem się dokumentacją - dokładniej to opisaniem planów na kolejne sprinty

**Comment by hardzik96** [comment]
Dzisiaj zaczęłam tworzyć dokumentacje mojego wkładu w projekt , czyli moje zadania przy kolejnych sprintach, szczegolnie przy pierwszym .

**Comment by RafikMul** [comment]
Rozpoczęcie opisu własnego wkładu w projekt, ale brak możliwości dodania do opisu całego dokumentu. Sądzę, że problem ten będzie rozwiązany jutro jako priorytet.

**Comment by konrad966** [comment]
Dokumentacja została dokończona
