### ISSUE TITLE
Udoskonalenie bazy danych

### ISSUE THREAD

**Issue by Impognomik** [Impognomik/Projekcik#16]

**Comment by konrad966** [comment]
Dzisiaj poprawiłem kod PHP obsługi bazy danych. Kod działa, lecz wymaga usprawnień. Nie działa dodawanie danych zawierających polskie znaki. Dodatkowo formularz nie wygląda zbyt atrakcyjnie.  Należy także usprawnić wyświetlanie rekordów z bazy danych. Po poprawieniu struktury bazy danych kod będzie także musiał ulec zmianie. 

Poza tym starałem się poprawić i rozszerzyć strukturę bazy danych, ale napotkałem problem związany ze składnikami. W naszych założeniach każdy składnik miał być wybierany z listy dostępnych składników z bazy danych i dodawany do przepisu, lecz nie wiem jak umieszczać dane o składnikach w przepisie, aby wszystko działało według naszych założeń i planów na rozwój naszego projektu.

Jutro chcę rozwiązać przynajmniej niektóre napotkane przeze mnie problemy

**Comment by konrad966** [comment]
Baza danych wymaga jeszcze trochę pracy. Trzeba poprawić szczególnie jej strukturę oraz kodowanie polskich znaków. Zostawiamy to na następny sprint.
