### ISSUE TITLE
Nauka HTML

### ISSUE THREAD

**Issue by hardzik96** [Impognomik/Projekcik#2]

**Comment by hardzik96** [comment]
Dzisiaj zdążyłam już sporo sobie poczytać o podstawach HTML-u , ale myślę że jeszcze brakuje mi trochę wiedzy na ten temat, więc muszę jeszcze poświęcić temu trochę czasu

**Comment by hardzik96** [comment]
Ogólnie to polecam tak na rozgrzewkę:
http://pl.html.net/tutorials/html/

**Comment by RafikMul** [comment]
Tworze próbne strony oraz szukam przykładowych szablonów stron internetowych.

**Comment by RafikMul** [comment]
Przeglądam ogólny wygląd stron typu książek kucharskich.

**Comment by RafikMul** [comment]
Kilka stron które mogą posłużyć jako przykłady jak ma wyglądać nasza strona:
https://www.przepisy.pl/
http://www.doradcasmaku.pl/przepisy
http://ugotuj.to/ugotuj/0,0.html
http://www.mniammniam.com/
http://gotujmy.pl/przepisy.html

**Comment by hardzik96** [comment]
Wczoraj przeglądałam szablony i podjęłam próby pisania prostych stron przy użyciu HTML.

**Comment by hardzik96** [comment]
Dzisiaj, przy pomocy kolegi , który udostępnił mi dostęp do panelu administracyjnego strony, byłam w stanie zobaczyć jak wygląda strona internetowa od strony technicznej. Myślę, że była to przydatna lekcja i dzięki niej mogłam mniej więcej ocenić pracę jaka nas czeka przy tworzeniu własnej strony.

**Comment by RafikMul** [comment]
Dziś nauczyłem się korzystać z programu Sway dzięki któremu nauczyłem się tworzyć graficzny układ podglądowy strony. Dzięki tej umiejętności łatwiej będzie napisanie strony ze względu na wiadome jak strona ma wyglądać.

**Comment by hardzik96** [comment]
Moja dzisiejsza praca polegała na stworzeniu strony poprzez domenę fora.pl oraz eksperymentowanie w panelu administracyjnym na wiele sposobów - zmiana tła strony oraz jej układu , zarządzanie użytkownikami oraz nadawanie użytkownikom pewnych uprawnień (rangi). Dodatkowo poznałam takie własności jak tworzenie listy słów cenzurowanych , listy emotikon itd.

**Comment by RafikMul** [comment]
Nauczyłem się tworzyć animację, dodawać obrazy, tworzyć teksty w różnych typach czcionki. Dodawanie prostych zmian w układzie strony. Nauka zapisu danych dodawanych przez użytkowników na stronę.

**Comment by RafikMul** [comment]
Nauczyłem się tworzyć animację, dodawać obrazy, tworzyć teksty w różnych typach czcionki. Dodawanie prostych zmian w układzie strony. Nauka zapisu danych dodawanych przez użytkowników na stronę.

**Comment by RafikMul** [comment]
Dzisiaj przerobiłem cały kurs HTML na stronie http://miroslawzelent.pl/kurs-html/. Jutro planuję zacząć tworzyć "korzeń" strony i dodać tło oraz menu. Mam zamiar nauczyć się podłączenia bazy danych do naszej strony i podłączyć przykładową bazę pod stronę oraz sprawdzić działanie tej operacji.

**Comment by hardzik96** [comment]
Dziś przeszłam internetowy kurs HTML z powodzeniem (tak mi się przynajmniej wydaje) i skupiłam się na możliwościach HTML jeżeli chodzi o formę przedstawienia tekstu oraz wgłębiłam się w zarządzanie innymi użytkownikami, tworzenie powiadomień, zmianę ustawień strony z domyślnych na własne , tworzenie własnych szablonów.

**Comment by hardzik96** [comment]
Uważam, że mój poziom znajomości HTML jest już wysoki i cel pierwszego sprintu , jakim było przyswojenie nowych informacji ( w moim przypadku głównie związanych z HTML) został osiągnięty

**Comment by RafikMul** [comment]
Dziś nauczyłem się ostatnich rzeczy dotyczących dotyczących języka HTML. Sądzę że perfekcyjnie umiem tworzyć podstawowe strony WWW.
