### ISSUE TITLE
Zapoznanie się i nauczenie korzystania z GIT'a

### ISSUE THREAD

**Issue by hardzik96** [Impognomik/Projekcik#5]

**Comment by hardzik96** [comment]
powoli się oswajam. Myślę , że wkrótce ogarnę całość

**Comment by konrad966** [comment]
Tak samo, powoli się oswajam. Miałem problemy ze stworzeniem repozytorium na komputerze, ale rozwiązałem go.

**Comment by Impognomik** [comment]
Dzisiaj stworzyłam repozytorium lokalne i synchronizowałam je z repozytorium zdalnym. Wykorzystałam do tego narzędzie git bash. Nauczyłam się korzystać z poleceń:
- git commit
- git push
- git checkout
- git init
- git branch
- git status

Stworzyłam plik README.md 

i nauczyłam się tworzyć kropki :)

**Comment by konrad966** [comment]
Zrobiłem pierwszy, testowy commit. Myślę, że już umiem korzystać z GIT

**Comment by hardzik96** [comment]
Zrobiłam pierwszy commit. Dlaczego wyszedł razy 3 ( trzy pliki)? Bo zapomniałam swojego hasła i się męczyłam trzy razy a potem wszystkie pliki na raz znalazły się w repozytorium. Brawo ja ...Pomimo tego failu, uważam , że GIT nie jest mi już obcy i poznałam go w 99.9%

**Comment by RafikMul** [comment]
Dzisiaj nauczyłem się w korzystania w pełni Git'a.
