### ISSUE TITLE
Projekt strony

### ISSUE THREAD

**Issue by RafikMul** [Impognomik/Projekcik#6]

**Comment by RafikMul** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/18568147/15094154/2782a522-149c-11e6-94ec-a6c24926093b.png)
 
przesyłam projekt graficzny utworzony w programie sway. Czekam na wszelakie uwagi

**Comment by RafikMul** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/18568147/15094161/99655572-149c-11e6-8707-38187ba3ff60.png)
Przesyłam układ graficzny strony utworzony w programie Sway. Czekam na wszelkie uwagi

**Comment by hardzik96** [comment]
no całkiem niezle powiedziałabym

**Comment by Impognomik** [comment]
Piękny, tylko może zamiast kwiatków pomyśleć o jakiś warzywach?

**Comment by RafikMul** [comment]
To wystarczy podrzucić grafikę, którą ustawimy jako rodzaj tła i będzie ona zmienna w zależności od tego co będziemy chcieli dokładnie uzyskać

**Comment by RafikMul** [comment]
![5](https://cloud.githubusercontent.com/assets/18568147/15100328/f7fb8584-156e-11e6-9dff-c72f9d848b25.jpg)

**Comment by RafikMul** [comment]
Możemy ustawić coś takiego

**Comment by hardzik96** [comment]
![jedz](https://cloud.githubusercontent.com/assets/18719865/15128533/9c0ae4e4-163c-11e6-8fb4-a3127aeaa85a.jpg)

**Comment by hardzik96** [comment]
a mi to bardziej do gustu przypadlo

**Comment by Impognomik** [comment]
nieco zbyt wielobarwne, może by to przerobić na jakąś sepie

**Comment by RafikMul** [comment]
Skorzystam z waszych grafik i  stworzę graficzny projekt.
