### ISSUE TITLE
Tworzenie kodu HTML

### ISSUE THREAD

**Issue by RafikMul** [Impognomik/Projekcik#9]

**Comment by hardzik96** [comment]
Dziś po raz pierwsze zabrałam się do pisania kodu , który zostanie wykorzystany do tworzenia naszej strony. Pracy jest dużo , ale myślę, że powoli jakoś wszystko się zrobi. Jak na razie to bardziej planuje co trzeba będzie napisać niż piszę , ponieważ bez dobrego planu się nie obejdzie

**Comment by RafikMul** [comment]
Napisałem dziś kilka linijek kodu po czym okazało się że nie działają próbowałem kilka razy rozwiązać problem. Po n-tym razie się udało. Uważam, że początek jest marny ale postaram się jutro wrzucić utworzony kod i zobaczycie moją pracę a także współpracownicy będą mogli zacząć korzystać z podstaw i dopisywać kolejne linie kodu.

**Comment by hardzik96** [comment]
Myśle , że to dobry pomysł bo nie ma to najmniejszego sensu jak bedziemy tworzyc dwa rozne kody , bo potem nijak to sie nie zgra

**Comment by RafikMul** [comment]
[PRZEPISY.txt](https://github.com/Impognomik/Projekcik/files/266937/PRZEPISY.txt)

Przesyłam kod zastanawiam siwe dlaczego nie wyświetla mi się nagłówek strony

**Comment by hardzik96** [comment]
sprobuje rozwiazac ten problem i przejrzec kod

**Comment by hardzik96** [comment]
Dzisiaj starałam się poprawić ten kod i coś do niego dodać , ale nie zdążyłam jeszcze skończyć  , więc efekty mojej pracy wstawię jutro, bo na dzień dzisiejszy jest to "rozkopane" w wielu miejscach.

**Comment by hardzik96** [comment]
Niemniej jednak uważam  , że w istocie, kod został stworzony , ale wymaga on jednak pewnych ulepszeń , co będzie już celem kolejnego sprintu

**Comment by RafikMul** [comment]
Wysyłam plik gdzie jest dodane Opcja przepis dnia poprzez naciśniecie przekierowuje nas na nadą stronę np. kanał na Youtubie z filmem
[PRZEPISY.txt](https://github.com/Impognomik/Projekcik/files/269254/PRZEPISY.txt)

**Comment by RafikMul** [comment]
Również uważam, że można zamknąć dany temat i dopracować już stronę w następnym sprincie
